### ISSUE TITLE
import ogh throws KeyError: 'PROJ_LIB'

### ISSUE THREAD

**Issue by keckje** [Freshwater-Initiative/Observatory#37]
import ogh
Traceback (most recent call last):

  File "<ipython-input-2-47391c0e9755>", line 1, in <module>
    import ogh

  File "C:\ProgramData\Anaconda3\lib\site-packages\ogh\__init__.py", line 11, in <module>
    from .ogh import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\ogh\ogh.py", line 26, in <module>
    from mpl_toolkits.basemap import Basemap

  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 155, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']

  File "C:\ProgramData\Anaconda3\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None

KeyError: 'PROJ_LIB'

I updated my conda install before installing ogh with:
conda install -c conda-forge ogh

Any ideas on how to resolve this error?

**Comment by jphuong** [comment]
It looks like a few people have already encountered this PROJ_LIB problem. 
[basemap issues](https://github.com/matplotlib/basemap/issues/419)
